name: OMGTest this action locally with act
on: 
  push:
    branches:
      - 'main'
jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Test release
        uses: ./workflows/create-release
        with:
          releaseName: 'Github action test'
        env:
          INSTANA_BASE: ${{ secrets.INSTANA_BASE }}
          INSTANA_TOKEN: ${{ secrets.INSTANA_TOKEN }}
