name: docker-compose-actions-workflow
on: 
  push:
    branches:
      - 'main'
jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Test release
        uses: actions/create-release@v1
        with:
          releaseName: 'Github action test'
