# name: docker-compose-actions-workflow
# on: 
#   push:
#     branches:
#       - 'main'
# jobs:
#   test-release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Test release
#         uses: actions/create-release@v1
#         with:
#           releaseName: 'Github action test'
#         env:
#           INSTANA_BASE: ${{ secrets.INSTANA_BASE }}
#           INSTANA_TOKEN: ${{ secrets.INSTANA_TOKEN }}

uses: taimos/github-action-instana-release@%%version%%
with:
  releaseName: 'Deployed version 42'
env:
  INSTANA_BASE: ${{ secrets.INSTANA_BASE }}
  INSTANA_TOKEN: ${{ secrets.INSTANA_TOKEN }}