name: Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be used for the new release'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Notify instana on release
      uses: taimos/github-action-instana-release@v4
      env:
        INSTANA_BASE: ${{ secrets.INSTANA_BASE }}
        INSTANA_TOKEN: ${{ secrets.INSTANA_TOKEN }}
      with:
        releaseName: Commit ${{ github.event.head_commit.message }}
        releaseScope: >
          {
            "applications": [
              {
                "name": "All Services",
                "services": [
                  { "name": "zabbix-06-PHP" }
                ]
              }
            ]
          }
